package com.dev.publica_in_out;

/**
 * This class was automatically generated by the data modeler tool.
 */

import org.jbpm.document.Document;
import org.kie.api.task.TaskEvent;
import org.kie.api.task.model.Task;
import org.kie.api.task.model.TaskData;
import org.kie.api.task.TaskLifeCycleEventListener;
import org.json.JSONObject;
import org.json.JSONArray;

import java.util.concurrent.CompletableFuture;
import org.jbpm.document.Document;
import org.jbpm.document.Document;
import java.lang.reflect.Method;
import java.util.List;
import org.jbpm.document.Document;
import org.kie.api.task.TaskEvent;
import org.kie.api.task.model.Task;
import org.kie.api.task.TaskLifeCycleEventListener;
import org.jbpm.document.DocumentCollection;


import java.lang.reflect.Method;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;


public class RegistroTareaListener implements TaskLifeCycleEventListener {
    
    private static final String API_URL = "http://172.25.30.98:8082/documentos";

    @Override
    public void beforeTaskActivatedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskClaimedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskSkippedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskStartedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskStoppedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskCompletedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskFailedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskAddedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskExitedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskReleasedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskResumedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskSuspendedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskForwardedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskDelegatedEvent(TaskEvent event) { }
    @Override
    public void beforeTaskNominatedEvent(TaskEvent event) { }
    @Override
    public void afterTaskActivatedEvent(TaskEvent event) { }
    @Override
    public void afterTaskClaimedEvent(TaskEvent event) { }
    @Override
    public void afterTaskSkippedEvent(TaskEvent event) { }
    @Override
    public void afterTaskStartedEvent(TaskEvent event)  { }
    @Override
    public void afterTaskStoppedEvent(TaskEvent event) { }
    
    @Override
    public void afterTaskCompletedEvent(TaskEvent e) {
        try {
            List<String> documentosIds = new ArrayList<>();
            Map<String, Object> vars = e.getTask().getTaskData().getTaskOutputVariables();
    
            vars.forEach((k, v) -> {
                if (v instanceof Document) {
                    Document d = (Document) v;
                    documentosIds.add(d.getIdentifier());
                } else if (v instanceof DocumentCollection) {
                    DocumentCollection coll = (DocumentCollection) v;
                    coll.getDocuments().forEach(doc -> {
                        Document d = (Document) doc;
                        documentosIds.add(d.getIdentifier());
                    });
                }
            });
    
            if (!documentosIds.isEmpty()) {
                enviarIds(documentosIds);
            }
    
           
    
        } catch (Exception ex) {
            System.err.println("❌ Error en afterTaskCompletedEvent: " + ex.getMessage());
            ex.printStackTrace();
        }
    }





    
    private void enviarIds(List<String> uuids) {
        try {
            JSONArray jsonArray = new JSONArray();
            uuids.forEach(jsonArray::put);
            JSONObject payload = new JSONObject().put("documentIds", jsonArray);
    
            PeticionHTTP.ejecuta(API_URL, payload)
                .whenComplete((resp, err) -> {
                    if (err != null) err.printStackTrace();
                    else System.out.println("✅ Respuesta del backend: " + resp);
                });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }



    @Override
    public void afterTaskFailedEvent(TaskEvent event) { }
    @Override
    public void afterTaskAddedEvent(TaskEvent event) { }
    @Override
    public void afterTaskExitedEvent(TaskEvent event) { }
    @Override
    public void afterTaskReleasedEvent(TaskEvent event) { }
    @Override
    public void afterTaskResumedEvent(TaskEvent event) { }
    @Override
    public void afterTaskSuspendedEvent(TaskEvent event) { }
    @Override
    public void afterTaskForwardedEvent(TaskEvent event) { }
    @Override
    public void afterTaskDelegatedEvent(TaskEvent event) { }
    @Override
    public void afterTaskNominatedEvent(TaskEvent event) { }
}